# Use an official Node.js runtime as a parent image
FROM node:22

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages
RUN npm install

# Make port 5000 available to the world outside this container
EXPOSE 5173

# Run the app
CMD ["npm", "run", "dev"]